import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import BG from "../public/images/Sant-sport-background-logo.svg";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative bg-black h-screen">
          <div className="absolute inset-0">
            <Image
              src={BG}
              alt="Sant-sport-background-logo"
              title="Sant-sport-background-logo"
              className="object-cover w-full h-full"
              width={500}
              height={500}
            />
          </div>
          <div className="absolute inset-0 w-full h-screen bg-gradient-to-b from-black/10 to-black">
            <div className="relative">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
